using System.Collections;
using System.Collections.Generic;
using Unity.Cinemachine;
using UnityEngine;

namespace MiceToBeHome
{
    /// <summary>
    /// Cinemachine shot director. It does NOT move the camera transform (the CinemachineBrain does);
    /// it only chooses which virtual camera is live, so the Brain BLENDS between them
    /// (overview while editing -> zoom-in to the player when the chase starts).
    /// The rig itself is generated by Tools > Mice to be Home > Build Camera Rig.
    /// </summary>
    public class CameraController : MonoBehaviour
    {
        public static readonly Color BackgroundColor = new Color(0.15f, 0.12f, 0.12f);

        private const int ActivePriority = 100;
        private const int IdlePriority = 0;

        [Tooltip("Wide overview shot used in the menu / editing phase.")]
        [SerializeField] private CinemachineCamera frameCamera = null;

        [Tooltip("Close shot that follows the player during the chase.")]
        [SerializeField] private CinemachineCamera followCamera = null;

        [Tooltip("Dramatic close zoom used on defeat.")]
        [SerializeField] private CinemachineCamera loseCamera = null;

        private CinemachineBasicMultiChannelPerlin[] noises;
        private Coroutine shakeRoutine;

        public void Initialize(BalanceSettings balance, Vector3 center)
        {
            // The rig tool bakes framing/offsets; at runtime we just start on the overview shot.
            FrameGrid();
        }

        public void FrameGrid()
        {
            Activate(frameCamera);
        }

        public void Follow(Transform target)
        {
            if (followCamera != null)
            {
                followCamera.Follow = target;
            }
            Activate(followCamera);
        }

        public void PlayLoseZoom(Transform target)
        {
            if (loseCamera != null)
            {
                loseCamera.Follow = target;
            }
            Activate(loseCamera);
        }

        private void Activate(CinemachineCamera target)
        {
            SetPriority(frameCamera, target);
            SetPriority(followCamera, target);
            SetPriority(loseCamera, target);
        }

        private static void SetPriority(CinemachineCamera cam, CinemachineCamera active)
        {
            if (cam == null)
            {
                return;
            }
            cam.Priority = cam == active ? ActivePriority : IdlePriority;
        }

        /// <summary>Pulses Perlin noise on the virtual cameras for a hit / impact shake.</summary>
        public void Shake(float amplitude, float duration)
        {
            EnsureNoises();
            if (noises.Length == 0 || amplitude <= 0f || duration <= 0f)
            {
                return;
            }
            if (shakeRoutine != null)
            {
                StopCoroutine(shakeRoutine);
            }
            shakeRoutine = StartCoroutine(ShakeRoutine(amplitude, duration));
        }

        private IEnumerator ShakeRoutine(float amplitude, float duration)
        {
            float t = 0f;
            while (t < duration)
            {
                t += Time.unscaledDeltaTime;
                SetNoiseAmplitude(Mathf.Lerp(amplitude, 0f, t / duration));
                yield return null;
            }
            SetNoiseAmplitude(0f);
            shakeRoutine = null;
        }

        private void EnsureNoises()
        {
            if (noises != null)
            {
                return;
            }
            var list = new List<CinemachineBasicMultiChannelPerlin>();
            AddNoise(list, frameCamera);
            AddNoise(list, followCamera);
            AddNoise(list, loseCamera);
            noises = list.ToArray();
        }

        private static void AddNoise(List<CinemachineBasicMultiChannelPerlin> list, CinemachineCamera cam)
        {
            if (cam == null)
            {
                return;
            }
            var perlin = cam.GetComponent<CinemachineBasicMultiChannelPerlin>();
            if (perlin != null)
            {
                list.Add(perlin);
            }
        }

        private void SetNoiseAmplitude(float amplitude)
        {
            for (int i = 0; i < noises.Length; i++)
            {
                if (noises[i] != null)
                {
                    noises[i].AmplitudeGain = amplitude;
                }
            }
        }

#if UNITY_EDITOR
        public void EditorBind(CinemachineCamera frame, CinemachineCamera follow, CinemachineCamera lose)
        {
            frameCamera = frame;
            followCamera = follow;
            loseCamera = lose;
        }
#endif
    }
}
